### ISSUE TITLE
当前目录找不到PresentationFramework.dll

### ISSUE THREAD

**Issue by lxydw** [VBSSCBGroup/PLC2Tool#1]
> 未经处理的异常:  System.IO.FileNotFoundException: 未能找到文件“C:\Users\Administrator\Desktop\LXY\PresentationFramework.dll”。
>    在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
>    在 System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
>    在 System.IO.File.ReadAllBytes(String path)
>    在 PLC2Tool.Module1.PCL2Plugin(String path) 位置 C:\Users\15874\source\repos\PLC2Tool\PLC2Tool\Module1.vb:行号 99
>    在 PLC2Tool.Module1.Main() 位置 C:\Users\15874\source\repos\PLC2Tool\PLC2Tool\Module1.vb:行号 87
### ??? 这能找到才见了鬼了，这是什么操作??????????当前目录找PresentationFramework.dll，emmm

**Comment by telecomadm1145** [comment]
emm这是没有做完的功能

**Comment by telecomadm1145** [comment]
要加载的PresentationFramework.dll为修改过的PresentationFramework.dll

**Comment by telecomadm1145** [comment]
所以才会当前目录找PresentationFramework.dll

**Comment by telecomadm1145** [comment]
只有pcl插件功能需要PresentationFramework.dll修改，其他的功能都不需要

**Comment by telecomadm1145** [comment]
并且向导要求的是改注册表，而不是插件加载
