### ISSUE TITLE
bug:密码写任何的东西都会正确

### ISSUE THREAD

**Issue by lxydw** [VBSSCBGroup/PLC2Tool#2]
### 我本来以为密码是个玩笑
写任何的东西都会正确
结果 今天玩vs2022
git了一下 额 真要密码
但写错了 QAQ hhh
### 写任何的东西都会正确 : )

**Comment by telecomadm1145** [comment]
是的，这真的是一个玩笑，并不是一个bug

**Comment by telecomadm1145** [comment]
另外这个(错误)密码是写到注释里面的，只有两个密码会显示错误
